### ISSUE TITLE
Adding a cooldown timer

### ISSUE THREAD

**Issue by AndyReifman** [maniknarang/arsenal-reddit-bot#1]
It would be nice to add a cooldown timer to the bot to help with users spamming the command on reddit.

**Comment by maniknarang** [comment]
I added a [cool down](https://github.com/maniknarang/arsenal-reddit-bot/commit/e2ee70a86e6a89c06ce62e7aafc49b6a8010a3d8) this morning based on some suggestions on reddit. Do you think we can improve on this?
